SET IDENTITY_INSERT [dbo].[Interest] ON
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (0, 'Mexican Food')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (1, 'Politics')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (2, 'Art')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (3, 'Music')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (4, 'Nature')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (5, 'Dance')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (6, 'Technology')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (7, 'Cinema')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (8, 'Cooking')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (9, 'Animals')
INSERT INTO [dbo].[Interest] ([InterestId], [Item]) VALUES (10, 'Fitness')