SET IDENTITY_INSERT [dbo].[InterestEntity] ON
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (0, N'Music')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (1, N'Cinema')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (2, N'Photography')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (3, N'Nature')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (4, N'Dancing')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (5, N'Watching TV')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (6, N'Poetry')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (7, N'Painting')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (8, N'Cooking')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (9, N'Collecting Antiques')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (10, N'Knitting')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (11, N'Sewing')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (12, N'Crafts')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (13, N'Debate')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (14, N'Playing Cards')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (15, N'Magic')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (16, N'Watching Cartoons')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (17, N'Adventurous Sports')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (18, N'Fishing')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (19, N'Horseback Riding')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (20, N'PC Games')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (21, N'Videogames')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (22, N'Sports')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (23, N'Roadtrips')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (24, N'Chess')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (25, N'Space')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (26, N'Travelling')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (27, N'Art')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (28, N'Books')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (29, N'Animals')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (30, N'Fitness')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (31, N'Wine')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (32, N'Restaurants')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (33, N'Live Music')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (34, N'Dogs')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (35, N'Politics')
INSERT INTO [dbo].[InterestEntity] ([InterestId], [Item]) VALUES (36, N'Sailing')
SET IDENTITY_INSERT [dbo].[InterestEntity] OFF
